FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install essential system dependencies
RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc && \
    apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /


COPY requirements.txt requirements.txt
COPY pyproject.toml pyproject.toml
COPY src/ src/


RUN pip install --no-cache-dir -r requirements.txt && \
    pip install . --no-deps --no-cache-dir

# Run DVC pull to fetch the dataset
RUN dvc init --no-scm
COPY .dvc/config .dvc/config
COPY *.dvc .dvc/
COPY data.dvc data.dvc
RUN dvc config core.no_scm true
RUN dvc pull

COPY . .
# Set the entrypoint to execute the training script
ENTRYPOINT ["python", "-u"]



