name: Unit Tests

on:
  push:
    branches:
      - main
      - Unit_Test # remove this line
  pull_request:
    branches:
      - main

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install DVC
        run: |
          pip install dvc
          pip install dvc-gs

      - name: Pull DVC-tracked dataset
        run: |
          dvc pull

      - name: Upload dataset artifact
        uses: actions/upload-artifact@v4
        with:
          name: permanent-dataset
          path: ./data

  test:
    runs-on: ${{ matrix.operating-system }}
    needs: create-artifact
    strategy:
      matrix:
        operating-system: ["windows-latest"]
        python-version: ["3.11", "3.12"]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      # Install other dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
          pip install numpy
          pip install torchvision

      - name: Download dataset artifact
        uses: actions/download-artifact@v4
        with:
          name: permanent-dataset
          path: ./data

      # Run tests and coverage, excluding test_data.py
      - name: Run tests & coverage
        run: | # "pytest tests" runs all tests in the tests directory
          pytest tests --ignore=tests/test_data.py 