name: Unit Tests

on:
  push:
    branches:
      - main
      - Unit_Test
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dataset artifact
        uses: actions/download-artifact@v3
        with:
          name: permanent-dataset
          path: ./data

      - name: Run tests
        run: |
          pytest .\tests\ --ignore=tests/test_data.py