name: Unit Tests

on:
  push:
    branches:
      - main
      - Unit_Test
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dataset artifact
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts" | \
          jq '.artifacts[] | select(.name == "permanent-dataset") | .id' | \
          xargs -I {} curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -o artifact.zip "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/{}/download"

      - name: Run tests
        run: |
          pytest .\tests\